# 1. Notifications
notifications:
  slack:
    rooms:
      - secure: "LWdWCYRMI758ZSVPX2223PrZnGJIK7YhB49p3kPChnHag4OfOc3WhKBZ1de8wrapg4MrbzvnkNwGDvvw1PQdqaL/OvgO+7Qz8frhSbUe9fdD5ohW+q2C3OdZTFxDM04ex2HL2yDnGJEz8FcTYpd1dC+14fxeri98Iz2Bj2vtlgnS8lClRq5rZelZMIALphzWnvy1i8tnq/595mWc31QrU8gfxvEcBNBChpknsTLujqHVOWHipvPEcWN7MhrD/dz8NhkBKSbtVLym0U+3Ezr51CDWAhy7NYAYf9FSGgcWrRQTtnr1xa8NsEO7zzcAJqTtBQebRGI0AJJQb7etHrlcNCxAwRk5OIwAloUDrfFnCdVVYogik4l/gqojQ97cmvYaFAuK+Pz/G91pEllWRvMAdKpfUvYO45JwD7CqCCInkGd5/sx7QG+GcaGZyuz1X8O7AR2WB4RV4lLi6XbUglhd1K3hQKTbZO70cprWISShGKK8hxrHP9iMfgnNdr+GnSmdY2FOtUXE5qoc4F2+rB/PV8t9jNjelSoK0uzn+Zzxw37whyJuU1MPU02/4R1CMs9gl9yDxOfORJYE8KNPtKddboasYTkoWrahbcRPdejN/Vzg9zwDiZcxtZlgpfRqU+HSbn0sID0DUgXCsteo4cV97qzHRV5t5RRj1vYsXes5jtE=" # atex-ci
      - secure: "gbiHuyhQ9zHH41ZwXfPwJ7M+lQdnLdVG8oHrCF1spUDVEPze0MiLFCWe0OUStH+ORgLbtGyE6h1kOcFUaxD/Ud37aSU/JUA8FaHHaQmzFmfv7wQcoMX/Y5n9n8mAb9+PpQfdqSb9b3+2DTKbjqEEDTm/S6PCf6IW4oRz1nJUIHXA8CTCKDxvxo+G3DOYAVo0QGEle37t0cmbjfxcWk86TwtEGgg6EFjGPtFNQHrwioukgrkYmS8mSGYItTmA2NyGtGb9u5edt8a9hvPROwtg0VhG3yL/UaPeKAr0KXEMwkJP7yl9mi3mNI2GQL7b9cxJp/OtILMqCOCpbJ3vdgxjFDEpYFvv767/blxInwl4T0ipE0yiqk8zVeSzPzrj94CHNwZWCmtJiJcCIu4AbQHc+jZOHBjRaCqEyN5oRCp91myRkqy1LzF6VgijarWWzEWRRSY1Y5yno3fPqdD9HAbStBHJ2T08gZ0UvFv7xv2fJZJb9NWSKTB/5w9aWqKq0vmNXZ4BnkfEBVbuxtaIC0f67MWeDnYwvSBp+zsaUwZJHdGqsRjmxmVBCaNOgZ9oShgl52CyZo7xS1pWDMNZvX1ECSn2XJgOUvJg+grjurqD9NKGyO1EMjnuDKpPVh/ZaCdC9FMdB6CbAXmG8H/Cz3sTCzoWkpnyitmMSJ9n1Ked8rk=" # cloud-ci
    on_success: change
    on_pull_requests: false

# 2. Env
# env:

# 3. Git
# git:
branches:
  except:
    - /^f\// # feature branches require PR
    - /^v\d+\.\d+\.\d+$/ # npm-publish-git

# 4. Bootstrap
os: linux
dist: trusty
sudo: false
language:
  - node_js
node_js:
  - node
# addons:
before_cache: ./.travis.sh before_cache
cache:
  directories:
    - $HOME/.local
    - $HOME/.npm
    - $HOME/.pip-cache/
    - $HOME/Library/Caches/Homebrew
    - /tmp/support-firecloud.cache

# 5. Steps
before_install: ./.travis.sh before_install
install: ./.travis.sh install
before_script: ./.travis.sh before_script
script: ./.travis.sh script
after_success: ./.travis.sh after_success
after_failure: ./.travis.sh after_failure
after_script: ./.travis.sh after_script

# 6. Deploy
before_deploy: ./.travis.sh before_deploy
# deploy:
after_deploy: ./.travis.sh after_deploy
